name: hamed_portfolio
description: Hamed Kazemi's Flutter Developer Portfolio
publish_to: "none"
build_number: 1.0.1+1
version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  flutter_svg: ^2.0.9
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  lucide_icons_flutter: ^3.1.0
  font_awesome_flutter: ^10.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
